# ベースイメージ
FROM ruby:3.1.2

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    curl \
    git \
    mecab \
    libmecab-dev \
    mecab-ipadic-utf8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Node.js 18 & Yarn をインストール
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

# 作業ディレクトリの設定
WORKDIR /app

# Gemfile と Gemfile.lock をコピー
COPY Gemfile Gemfile.lock ./

# Bundlerのインストールとgem依存関係のインストール（開発環境用）
RUN gem install bundler && \
    bundle install

# package.json と yarn.lock をコピー
COPY package.json yarn.lock ./

# Node.js依存関係のインストール
RUN yarn install

# アプリケーションコードをコピー
COPY . .

# assets を事前コンパイル
RUN bundle exec rails assets:precompile

RUN mkdir -p tmp/pids

# エントリーポイントスクリプトをコピーして実行権限を付与
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

# エントリーポイントの設定
ENTRYPOINT ["entrypoint.sh"]

# ポート3000を公開
# EXPOSE 3000

# Railsサーバーを起動
# CMD ["rails", "server", "-b", "0.0.0.0"]
